### ISSUE TITLE
lmfaoooooooooooooooooooooooooo

### ISSUE THREAD

**Issue by FlorianJester** [davidhawes/Springboot-WebApp#1]
bing chilling 😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂

**Comment by davidhawes** [comment]
I fix the issue

**Comment by FlorianJester** [comment]
Fakest thing ever

**Comment by davidhawes** [comment]
**I fixed the issue u basterd 😉😉😉😉😊😊😊🙌🙌🙌🙌👍👍👍👍🤣🤣🤣🤣🤣🤣**

**Comment by FlorianJester** [comment]
Reported :(
![IMG_5502](https://github.com/davidhawes/Springboot-WebApp/assets/76409979/1bfe0595-aaa5-4258-88f1-69a35a1bd51b)

**Comment by davidhawes** [comment]
holy fuck alcoholic fun time
